server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vuemanager?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    # username和password指向数据库的用户名和密码
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
